### ISSUE TITLE
Temporary directory is not deleted when finished

### ISSUE THREAD

**Issue by hadjiprocopis** [uperl/Test-Script#43]
I observe a number of temporary directories in the current working dir named like ```.test-script-Fs2BZZzY``` when tests are passed and the test file exits gracefully. Am I doing something wrong? Can they be deleted automatically?

**Comment by plicease** [comment]
Those files should be cleaned up automatically if the test script exits normally because this module uses the `CLEANUP` option when creating those directories:

https://github.com/uperl/Test-Script/blob/2f315fbb9888fc860495f26e778d6bbc6dd0137c/lib/Test/Script.pm#L185-L190

unless `File::Temp` or `Test::Script` has been tampered with I am not sure why it would leave these files.

**Comment by hadjiprocopis** [comment]
I think I know why:

In my test script I use the logic that if the test fails and exits via a ```BAIL_OUT```, *my* tempfiles should not be cleanup'ed automatically but stay for inspection. This is done like this:
```
# at the beginning
$File::Temp::KEEP_ALL = 1;
...
# at the end, when test succeeds:
$File::Temp::KEEP_ALL = 0; File::Temp::cleanup();
```

When I saw the test-files remaining and reported the error I had the ```$File::Temp::KEEP_ALL = 0; File::Temp::cleanup();``` commented out for some reason. And that prevented *your* tempfiles to remain as well.

Here is a test script to replicate:

```
#!/usr/bin/env perl

use strict;
use warnings;

use Test::More;
use Test::Script;
use File::Temp;

our $VERSION = '0.06';

$File::Temp::KEEP_ALL = 1;

# just a random, non-existent script,
# test will fail but it does not matter
my $cmdline = ['blababla', '--abc'];
script_runs($cmdline, 'test');

# END
done_testing();

# comment this to see .test-... dirs remaining after exit
#$File::Temp::KEEP_ALL = 0; File::Temp::cleanup();
```

I can leave with this. And it is a very rare use of ```File::Temp```, so perhaps this is an irrelevant issue.

Many thanks

**Comment by plicease** [comment]
Cool, thanks for getting back to me.  I think this is within the expected behavior so I will close.
